#!/usr/bin/env python3
"""
Sous-patch 3/3 du systeme d'ancrage entre objets (style Canva/Figma). Ajoute :
  1) Une ligne de guidage ne peut se creer qu'avec un objet dont la boite
     englobante est actuellement visible a l'ecran (les objets scrolles hors
     champ sont ignores).
  2) Pour un trait fin (epaisseur <= 3pt) horizontal ou vertical, un seul
     point d'ancrage est propose sur l'axe de l'epaisseur (le milieu),
     au lieu de 3 quasi-identiques (haut/milieu/bas ou gauche/milieu/droite).
  3) Le snap-grille existant ne vient plus perturber legerement un axe deja
     aligne precisement par le snap d'objet (evite le petit decalage
     constate entre un objet selectionne et sa copie non selectionnee).
  4) La ligne de guidage devient VERTE quand l'alignement implique le point
     d'ancrage centre de l'un des deux objets (rose sinon, pour un bord).

NECESSITE apply_alignment_snap_v1.py ET apply_alignment_snap_v2.py deja
appliques, dans cet ordre.
A lancer depuis la racine du depot xournalpp.
"""
import sys
from pathlib import Path


def apply_edit(path: Path, old: str, new: str, label: str) -> bool:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count == 0:
        if text.count(new) > 0:
            print(f"[SKIP]  {label}: déjà appliqué.")
            return True
        print(f"[ECHEC] {label}: motif introuvable dans {path}")
        return False
    if count > 1:
        print(f"[ECHEC] {label}: motif trouvé {count} fois dans {path} (doit être unique)")
        return False
    text = text.replace(old, new, 1)
    path.write_text(text, encoding="utf-8")
    print(f"[OK]    {label}")
    return True


def main():
    cpp = Path("src/core/control/tools/EditSelection.cpp")
    h = Path("src/core/control/tools/EditSelection.h")
    if not cpp.exists():
        print("[ECHEC] EditSelection.cpp introuvable. Lancez ce script depuis la racine du dépôt xournalpp.")
        sys.exit(1)
    if "activeGuideX" not in cpp.read_text(encoding="utf-8"):
        print("[ECHEC] activeGuideX introuvable dans EditSelection.cpp.")
        print("        Appliquez d'abord apply_alignment_snap_v1.py puis apply_alignment_snap_v2.py.")
        sys.exit(1)

    ok = True

    ok &= apply_edit(
        h,
        old='    struct AlignmentGuide {\n'
            '        double coordinate;\n'
            '        double from;\n'
            '        double to;\n'
            '    };',
        new='    struct AlignmentGuide {\n'
            '        double coordinate;\n'
            '        double from;\n'
            '        double to;\n'
            '        bool isCenter;\n'
            '    };',
        label="EditSelection.h: champ isCenter dans AlignmentGuide",
    )

    ok &= apply_edit(
        cpp,
        old='/**\n'
            ' * Result of a successful alignment match: `offset` is the amount to shift the moving object\'s\n'
            ' * coordinate to align exactly; `coordinate` is the aligned value itself (for drawing the guide\n'
            ' * line); `extentFrom`/`extentTo` delimit, on the perpendicular axis, the segment spanning both the\n'
            ' * moving object and the matched object, so the drawn guide line visually connects the two.\n'
            ' */\n'
            'struct AlignmentMatch {\n'
            '    double offset;\n'
            '    double coordinate;\n'
            '    double extentFrom;\n'
            '    double extentTo;\n'
            '};\n\n'
            '/**\n'
            ' * If any of the moving box\'s 3 horizontal candidates (top / vertical-center / bottom), when placed\n'
            ' * at the given y with the given height, is within `tolerance` (document units) of the corresponding\n'
            ' * candidate of another element on `layer` (elements in `excluded` are skipped - i.e. the elements\n'
            ' * currently being moved), returns the match. Returns nullopt otherwise.\n'
            ' * xLeft/xRight are the moving box\'s horizontal extent, used together with the matched element\'s own\n'
            ' * extent to compute the guide line\'s span (perpendicular axis).\n'
            ' */\n'
            'static auto findAlignmentY(double y, double height, double xLeft, double xRight, double tolerance, Layer* layer,\n'
            '                            const std::vector<const Element*>& excluded) -> std::optional<AlignmentMatch> {\n'
            '    const double candidatesSelf[3] = {y, y + height / 2, y + height};\n'
            '    std::optional<AlignmentMatch> best;\n'
            '    double bestDist = tolerance;\n'
            '    for (auto& elPtr: layer->getElements()) {\n'
            '        const Element* el = elPtr.get();\n'
            '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
            '            continue;\n'
            '        }\n'
            '        double eh = el->getElementHeight();\n'
            '        double ey = el->getY();\n'
            '        double ew = el->getElementWidth();\n'
            '        double ex = el->getX();\n'
            '        const double candidatesOther[3] = {ey, ey + eh / 2, ey + eh};\n'
            '        for (double cs: candidatesSelf) {\n'
            '            for (double co: candidatesOther) {\n'
            '                double dist = std::abs(cs - co);\n'
            '                if (dist < bestDist) {\n'
            '                    bestDist = dist;\n'
            '                    best = AlignmentMatch{co - cs, co, std::min(xLeft, ex), std::max(xRight, ex + ew)};\n'
            '                }\n'
            '            }\n'
            '        }\n'
            '    }\n'
            '    return best;\n'
            '}\n\n'
            '/// Same as findAlignmentY(), but for the 3 vertical candidates (left / horizontal-center / right).\n'
            '/// yTop/yBottom are the moving box\'s vertical extent, used for the guide line\'s span.\n'
            'static auto findAlignmentX(double x, double width, double yTop, double yBottom, double tolerance, Layer* layer,\n'
            '                            const std::vector<const Element*>& excluded) -> std::optional<AlignmentMatch> {\n'
            '    const double candidatesSelf[3] = {x, x + width / 2, x + width};\n'
            '    std::optional<AlignmentMatch> best;\n'
            '    double bestDist = tolerance;\n'
            '    for (auto& elPtr: layer->getElements()) {\n'
            '        const Element* el = elPtr.get();\n'
            '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
            '            continue;\n'
            '        }\n'
            '        double ew = el->getElementWidth();\n'
            '        double ex = el->getX();\n'
            '        double eh = el->getElementHeight();\n'
            '        double ey = el->getY();\n'
            '        const double candidatesOther[3] = {ex, ex + ew / 2, ex + ew};\n'
            '        for (double cs: candidatesSelf) {\n'
            '            for (double co: candidatesOther) {\n'
            '                double dist = std::abs(cs - co);\n'
            '                if (dist < bestDist) {\n'
            '                    bestDist = dist;\n'
            '                    best = AlignmentMatch{co - cs, co, std::min(yTop, ey), std::max(yBottom, ey + eh)};\n'
            '                }\n'
            '            }\n'
            '        }\n'
            '    }\n'
            '    return best;\n'
            '}\n\n'
            'void EditSelection::mouseMove(double mouseX, double mouseY, bool alt) {\n'
            '    double zoom = this->view->getXournal()->getZoom();\n\n'
            '    if (this->mouseDownType == CURSOR_SELECTION_MOVE) {',
        new='/**\n'
            ' * Result of a successful alignment match: `offset` is the amount to shift the moving object\'s\n'
            ' * coordinate to align exactly; `coordinate` is the aligned value itself (for drawing the guide\n'
            ' * line); `extentFrom`/`extentTo` delimit, on the perpendicular axis, the segment spanning both the\n'
            ' * moving object and the matched object, so the drawn guide line visually connects the two.\n'
            ' * `isCenter` is true if either of the two matched candidates was a center point (rather than an\n'
            ' * edge), used to draw the guide line in a different color.\n'
            ' */\n'
            'struct AlignmentMatch {\n'
            '    double offset;\n'
            '    double coordinate;\n'
            '    double extentFrom;\n'
            '    double extentTo;\n'
            '    bool isCenter;\n'
            '};\n\n'
            '/// A single candidate coordinate for alignment, tagged with whether it is a center point.\n'
            'struct AlignmentCandidate {\n'
            '    double value;\n'
            '    bool isCenter;\n'
            '};\n\n'
            '/**\n'
            ' * Below this size (in document points), a box is considered to have no meaningful "thickness axis"\n'
            ' * of its own (e.g. a horizontal or vertical straight line) - see buildCandidates().\n'
            ' */\n'
            'constexpr double THIN_AXIS_THRESHOLD = 3.0;\n\n'
            '/**\n'
            ' * Builds the 1 or 3 alignment candidates for a box spanning [from, from + size] on one axis. If the\n'
            ' * box is "thin" on that axis (size <= THIN_AXIS_THRESHOLD, e.g. the thickness of a horizontal or\n'
            ' * vertical line), only the center candidate is returned: offering top/bottom (or left/right)\n'
            ' * candidates as well would produce two near-identical, confusingly close guide lines for a simple\n'
            ' * straight line.\n'
            ' */\n'
            'static auto buildCandidates(double from, double size) -> std::vector<AlignmentCandidate> {\n'
            '    if (size <= THIN_AXIS_THRESHOLD) {\n'
            '        return {{from + size / 2, true}};\n'
            '    }\n'
            '    return {{from, false}, {from + size / 2, true}, {from + size, false}};\n'
            '}\n\n'
            '/// True if the two given [x, x+w] x [y, y+h] boxes intersect at all.\n'
            'static auto boxesIntersect(double x1, double y1, double w1, double h1, double x2, double y2, double w2, double h2)\n'
            '        -> bool {\n'
            '    return x1 <= x2 + w2 && x2 <= x1 + w1 && y1 <= y2 + h2 && y2 <= y1 + h1;\n'
            '}\n\n'
            '/**\n'
            ' * If any of the moving box\'s y-candidates (see buildCandidates()), when placed at the given y with\n'
            ' * the given height, is within `tolerance` (document units) of the corresponding candidate of\n'
            ' * another element on `layer`, returns the match. Candidates are only considered for elements whose\n'
            ' * bounding box currently intersects `visibleRect` (elements scrolled out of view are ignored), and\n'
            ' * elements in `excluded` are always skipped (i.e. the elements currently being moved).\n'
            ' * xLeft/xRight are the moving box\'s horizontal extent, used together with the matched element\'s own\n'
            ' * extent to compute the guide line\'s span (perpendicular axis).\n'
            ' */\n'
            'static auto findAlignmentY(double y, double height, double xLeft, double xRight, double tolerance, Layer* layer,\n'
            '                            const std::vector<const Element*>& excluded,\n'
            '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
            '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(y, height);\n'
            '    std::optional<AlignmentMatch> best;\n'
            '    double bestDist = tolerance;\n'
            '    for (auto& elPtr: layer->getElements()) {\n'
            '        const Element* el = elPtr.get();\n'
            '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
            '            continue;\n'
            '        }\n'
            '        double eh = el->getElementHeight();\n'
            '        double ey = el->getY();\n'
            '        double ew = el->getElementWidth();\n'
            '        double ex = el->getX();\n'
            '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
            '            continue;\n'
            '        }\n'
            '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(ey, eh);\n'
            '        for (auto& cs: candidatesSelf) {\n'
            '            for (auto& co: candidatesOther) {\n'
            '                double dist = std::abs(cs.value - co.value);\n'
            '                if (dist < bestDist) {\n'
            '                    bestDist = dist;\n'
            '                    best = AlignmentMatch{co.value - cs.value, co.value, std::min(xLeft, ex), std::max(xRight, ex + ew),\n'
            '                                           cs.isCenter || co.isCenter};\n'
            '                }\n'
            '            }\n'
            '        }\n'
            '    }\n'
            '    return best;\n'
            '}\n\n'
            '/// Same as findAlignmentY(), but for the horizontal candidates (left / horizontal-center / right).\n'
            '/// yTop/yBottom are the moving box\'s vertical extent, used for the guide line\'s span.\n'
            'static auto findAlignmentX(double x, double width, double yTop, double yBottom, double tolerance, Layer* layer,\n'
            '                            const std::vector<const Element*>& excluded,\n'
            '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
            '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(x, width);\n'
            '    std::optional<AlignmentMatch> best;\n'
            '    double bestDist = tolerance;\n'
            '    for (auto& elPtr: layer->getElements()) {\n'
            '        const Element* el = elPtr.get();\n'
            '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
            '            continue;\n'
            '        }\n'
            '        double ew = el->getElementWidth();\n'
            '        double ex = el->getX();\n'
            '        double eh = el->getElementHeight();\n'
            '        double ey = el->getY();\n'
            '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
            '            continue;\n'
            '        }\n'
            '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(ex, ew);\n'
            '        for (auto& cs: candidatesSelf) {\n'
            '            for (auto& co: candidatesOther) {\n'
            '                double dist = std::abs(cs.value - co.value);\n'
            '                if (dist < bestDist) {\n'
            '                    bestDist = dist;\n'
            '                    best = AlignmentMatch{co.value - cs.value, co.value, std::min(yTop, ey), std::max(yBottom, ey + eh),\n'
            '                                           cs.isCenter || co.isCenter};\n'
            '                }\n'
            '            }\n'
            '        }\n'
            '    }\n'
            '    return best;\n'
            '}\n\n'
            'void EditSelection::mouseMove(double mouseX, double mouseY, bool alt) {\n'
            '    double zoom = this->view->getXournal()->getZoom();\n\n'
            '    if (this->mouseDownType == CURSOR_SELECTION_MOVE) {',
        label="EditSelection.cpp: findAlignmentX/Y (visibilité + traits fins + centre)",
    )

    ok &= apply_edit(
        cpp,
        old='        // Smart alignment guides: snap the moving selection\'s bounding box edges/centers to those of\n'
            '        // other elements on the same layer, if close enough, and remember the match to draw a guide\n'
            '        // line connecting the two objects (see paint()).\n'
            '        if (settings != nullptr && settings->isSnapToObjects() && this->sourceLayer != nullptr &&\n'
            '            this->rotation == 0.0) {\n'
            '            double tolerance = ALIGNMENT_SNAP_TOLERANCE_PX / zoom;\n'
            '            std::vector<const Element*> excluded = this->getElementsView().clone();\n'
            '            double candidateX = this->snappedBounds.x + dx;\n'
            '            double candidateY = this->snappedBounds.y + dy;\n'
            '            double width = this->snappedBounds.width;\n'
            '            double height = this->snappedBounds.height;\n\n'
            '            auto matchX = findAlignmentX(candidateX, width, candidateY, candidateY + height, tolerance,\n'
            '                                          this->sourceLayer, excluded);\n'
            '            auto matchY = findAlignmentY(candidateY, height, candidateX, candidateX + width, tolerance,\n'
            '                                          this->sourceLayer, excluded);\n\n'
            '            if (matchX) {\n'
            '                dx += matchX->offset;\n'
            '                this->activeGuideX = AlignmentGuide{matchX->coordinate, matchX->extentFrom, matchX->extentTo};\n'
            '            } else {\n'
            '                this->activeGuideX.reset();\n'
            '            }\n'
            '            if (matchY) {\n'
            '                dy += matchY->offset;\n'
            '                this->activeGuideY = AlignmentGuide{matchY->coordinate, matchY->extentFrom, matchY->extentTo};\n'
            '            } else {\n'
            '                this->activeGuideY.reset();\n'
            '            }\n'
            '        } else {\n'
            '            this->activeGuideX.reset();\n'
            '            this->activeGuideY.reset();\n'
            '        }\n\n'
            '        // find corner of reduced bounding box in rotated coordinate system closest to grabbing position\n'
            '        double cx = this->snappedBounds.x;\n'
            '        double cy = this->snappedBounds.y;\n'
            '        if ((this->relMousePosRotX > this->snappedBounds.width / 2) ==\n'
            '            (this->snappedBounds.width > 0)) {  // closer to the right side\n'
            '            cx += this->snappedBounds.width;\n'
            '        }\n'
            '        if ((this->relMousePosRotY > this->snappedBounds.height / 2) ==\n'
            '            (this->snappedBounds.height > 0)) {  // closer to the lower side\n'
            '            cy += this->snappedBounds.height;\n'
            '        }\n\n'
            '        // compute corner of reduced bounding box in unmodified coordinate system closest to grabbing position\n'
            '        cairo_matrix_t inv = this->cmatrix;\n'
            '        cairo_matrix_invert(&inv);\n'
            '        cx *= zoom;\n'
            '        cy *= zoom;\n'
            '        cairo_matrix_transform_point(&inv, &cx, &cy);\n'
            '        cx /= zoom;\n'
            '        cy /= zoom;\n\n'
            '        // compute position where unsnapped corner would move\n'
            '        Point p = Point(cx + dx, cy + dy);\n\n'
            '        // snap this corner\n'
            '        p = snappingHandler.snapToGrid(p, alt);',
        new='        // Smart alignment guides: snap the moving selection\'s bounding box edges/centers to those of\n'
            '        // other elements on the same layer, if close enough, and remember the match to draw a guide\n'
            '        // line connecting the two objects (see paint()). Only elements currently visible on screen\n'
            '        // are considered (an anchor point scrolled out of view would be a confusing match).\n'
            '        bool objectSnappedX = false;\n'
            '        bool objectSnappedY = false;\n'
            '        if (settings != nullptr && settings->isSnapToObjects() && this->sourceLayer != nullptr &&\n'
            '            this->rotation == 0.0) {\n'
            '            xoj::util::Rectangle<double>* visibleRectPtr = this->view->getXournal()->getVisibleRect(this->view);\n'
            '            if (visibleRectPtr != nullptr) {\n'
            '                xoj::util::Rectangle<double> visibleRect = *visibleRectPtr;\n'
            '                delete visibleRectPtr;\n\n'
            '                double tolerance = ALIGNMENT_SNAP_TOLERANCE_PX / zoom;\n'
            '                std::vector<const Element*> excluded = this->getElementsView().clone();\n'
            '                double candidateX = this->snappedBounds.x + dx;\n'
            '                double candidateY = this->snappedBounds.y + dy;\n'
            '                double width = this->snappedBounds.width;\n'
            '                double height = this->snappedBounds.height;\n\n'
            '                auto matchX = findAlignmentX(candidateX, width, candidateY, candidateY + height, tolerance,\n'
            '                                              this->sourceLayer, excluded, visibleRect);\n'
            '                auto matchY = findAlignmentY(candidateY, height, candidateX, candidateX + width, tolerance,\n'
            '                                              this->sourceLayer, excluded, visibleRect);\n\n'
            '                if (matchX) {\n'
            '                    dx += matchX->offset;\n'
            '                    objectSnappedX = true;\n'
            '                    this->activeGuideX =\n'
            '                            AlignmentGuide{matchX->coordinate, matchX->extentFrom, matchX->extentTo, matchX->isCenter};\n'
            '                } else {\n'
            '                    this->activeGuideX.reset();\n'
            '                }\n'
            '                if (matchY) {\n'
            '                    dy += matchY->offset;\n'
            '                    objectSnappedY = true;\n'
            '                    this->activeGuideY =\n'
            '                            AlignmentGuide{matchY->coordinate, matchY->extentFrom, matchY->extentTo, matchY->isCenter};\n'
            '                } else {\n'
            '                    this->activeGuideY.reset();\n'
            '                }\n'
            '            }\n'
            '        } else {\n'
            '            this->activeGuideX.reset();\n'
            '            this->activeGuideY.reset();\n'
            '        }\n\n'
            '        // find corner of reduced bounding box in rotated coordinate system closest to grabbing position\n'
            '        double cx = this->snappedBounds.x;\n'
            '        double cy = this->snappedBounds.y;\n'
            '        if ((this->relMousePosRotX > this->snappedBounds.width / 2) ==\n'
            '            (this->snappedBounds.width > 0)) {  // closer to the right side\n'
            '            cx += this->snappedBounds.width;\n'
            '        }\n'
            '        if ((this->relMousePosRotY > this->snappedBounds.height / 2) ==\n'
            '            (this->snappedBounds.height > 0)) {  // closer to the lower side\n'
            '            cy += this->snappedBounds.height;\n'
            '        }\n\n'
            '        // compute corner of reduced bounding box in unmodified coordinate system closest to grabbing position\n'
            '        cairo_matrix_t inv = this->cmatrix;\n'
            '        cairo_matrix_invert(&inv);\n'
            '        cx *= zoom;\n'
            '        cy *= zoom;\n'
            '        cairo_matrix_transform_point(&inv, &cx, &cy);\n'
            '        cx /= zoom;\n'
            '        cy /= zoom;\n\n'
            '        // compute position where unsnapped corner would move\n'
            '        Point p = Point(cx + dx, cy + dy);\n\n'
            '        // snap this corner to the grid - but not on an axis where an object-alignment guide already\n'
            '        // snapped it precisely above, or the grid could nudge it slightly off that exact alignment.\n'
            '        if (objectSnappedX && objectSnappedY) {\n'
            '            // both axes already precisely aligned to another object; leave p untouched\n'
            '        } else if (objectSnappedX) {\n'
            '            p.y = snappingHandler.snapVertically(p.y, alt);\n'
            '        } else if (objectSnappedY) {\n'
            '            p.x = snappingHandler.snapHorizontally(p.x, alt);\n'
            '        } else {\n'
            '            p = snappingHandler.snapToGrid(p, alt);\n'
            '        }',
        label="EditSelection.cpp: injection avec rect visible + désactivation sélective du snap grille",
    )

    ok &= apply_edit(
        cpp,
        old='    // Smart alignment guides: a bounded pink line connecting the moving selection to whichever\n'
            '    // element(s) it is currently aligned with.\n'
            '    if (this->activeGuideX || this->activeGuideY) {\n'
            '        cairo_save(cr);\n'
            '        cairo_set_line_width(cr, 1.5);\n'
            '        cairo_set_dash(cr, nullptr, 0, 0);\n'
            '        cairo_set_source_rgb(cr, 1.0, 0.0, 0.8);  // bright pink\n\n'
            '        if (this->activeGuideX) {\n'
            '            double gx = this->activeGuideX->coordinate * zoom;\n'
            '            cairo_move_to(cr, gx, this->activeGuideX->from * zoom);\n'
            '            cairo_line_to(cr, gx, this->activeGuideX->to * zoom);\n'
            '            cairo_stroke(cr);\n'
            '        }\n'
            '        if (this->activeGuideY) {\n'
            '            double gy = this->activeGuideY->coordinate * zoom;\n'
            '            cairo_move_to(cr, this->activeGuideY->from * zoom, gy);\n'
            '            cairo_line_to(cr, this->activeGuideY->to * zoom, gy);\n'
            '            cairo_stroke(cr);\n'
            '        }\n'
            '        cairo_restore(cr);\n'
            '    }\n',
        new='    // Smart alignment guides: a bounded line connecting the moving selection to whichever element(s)\n'
            '    // it is currently aligned with. Pink for an edge alignment, green if either matched anchor was a\n'
            '    // center point.\n'
            '    if (this->activeGuideX || this->activeGuideY) {\n'
            '        cairo_save(cr);\n'
            '        cairo_set_line_width(cr, 1.5);\n'
            '        cairo_set_dash(cr, nullptr, 0, 0);\n\n'
            '        if (this->activeGuideX) {\n'
            '            if (this->activeGuideX->isCenter) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.8, 0.2);  // green\n'
            '            } else {\n'
            '                cairo_set_source_rgb(cr, 1.0, 0.0, 0.8);  // bright pink\n'
            '            }\n'
            '            double gx = this->activeGuideX->coordinate * zoom;\n'
            '            cairo_move_to(cr, gx, this->activeGuideX->from * zoom);\n'
            '            cairo_line_to(cr, gx, this->activeGuideX->to * zoom);\n'
            '            cairo_stroke(cr);\n'
            '        }\n'
            '        if (this->activeGuideY) {\n'
            '            if (this->activeGuideY->isCenter) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.8, 0.2);  // green\n'
            '            } else {\n'
            '                cairo_set_source_rgb(cr, 1.0, 0.0, 0.8);  // bright pink\n'
            '            }\n'
            '            double gy = this->activeGuideY->coordinate * zoom;\n'
            '            cairo_move_to(cr, this->activeGuideY->from * zoom, gy);\n'
            '            cairo_line_to(cr, this->activeGuideY->to * zoom, gy);\n'
            '            cairo_stroke(cr);\n'
            '        }\n'
            '        cairo_restore(cr);\n'
            '    }\n',
        label="EditSelection.cpp: rendu vert pour alignement centre dans paint()",
    )

    print()
    if ok:
        print("Toutes les modifications ont été appliquées avec succès.")
        sys.exit(0)
    else:
        print("Au moins une modification a échoué. Vérifiez le [ECHEC] ci-dessus.")
        sys.exit(1)


if __name__ == "__main__":
    main()
