#!/usr/bin/env python3
"""
Sous-patch 5/5 du systeme d'ancrage entre objets (style Canva/Figma). Ajoute :
  1) Retour a 0.5 (centre geometrique exact) pour le centre des traits fins
     horizontaux (annule le 0.7 du patch 4).
  2) Nouvelle constante dediee TEXT_Y_CENTER_FRACTION (0.2) pour le centre
     horizontal des Text, independante du cas "trait fin".
  3) Priorite en paliers : un match bleu (croisement petit/grand trait,
     centre-centre) prend le pas sur TOUS les autres matchs du meme axe ; un
     match vert (centre) prend le pas sur les matchs roses (bords). Ceci
     couvre aussi la demande de priorite verte du patch precedent.
  4) Plafond de 15pt sur la longueur du petit trait pour le declenchement
     bleu, EN PLUS d'un vrai test d'intersection de position (le petit trait
     doit reellement chevaucher l'etendue du grand trait, pas juste etre
     plus court quelque part sur la page).
  5) Bleu plus vif (electric blue).

NECESSITE apply_alignment_snap_v1.py, v2.py, v3.py et v4.py deja appliques,
dans cet ordre.
A lancer depuis la racine du depot xournalpp.
"""
import sys
from pathlib import Path


def apply_edit(path: Path, old: str, new: str, label: str) -> bool:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count == 0:
        if text.count(new) > 0:
            print(f"[SKIP]  {label}: déjà appliqué.")
            return True
        print(f"[ECHEC] {label}: motif introuvable dans {path}")
        return False
    if count > 1:
        print(f"[ECHEC] {label}: motif trouvé {count} fois dans {path} (doit être unique)")
        return False
    text = text.replace(old, new, 1)
    path.write_text(text, encoding="utf-8")
    print(f"[OK]    {label}")
    return True


def main():
    cpp = Path("src/core/control/tools/EditSelection.cpp")
    if not cpp.exists():
        print("[ECHEC] EditSelection.cpp introuvable. Lancez ce script depuis la racine du dépôt xournalpp.")
        sys.exit(1)
    content = cpp.read_text(encoding="utf-8")
    if "PERPENDICULAR_CROSS_BOOST_FACTOR" not in content:
        print("[ECHEC] PERPENDICULAR_CROSS_BOOST_FACTOR introuvable dans EditSelection.cpp.")
        print("        Appliquez d'abord apply_alignment_snap_v1/v2/v3/v4.py, puis relancez ce script.")
        sys.exit(1)

    ok = True

    ok &= apply_edit(
        cpp,
        old='#include "model/Point.h"                          // for Point\n'
            '#include "model/XojPage.h"                        // for XojPage',
        new='#include "model/Point.h"                          // for Point\n'
            '#include "model/Text.h"                           // for Text\n'
            '#include "model/XojPage.h"                        // for XojPage',
        label="EditSelection.cpp: include model/Text.h",
    )

    old_block = (
        '/**\n'
        ' * Result of a successful alignment match: `offset` is the amount to shift the moving object\'s\n'
        ' * coordinate to align exactly; `coordinate` is the aligned value itself (for drawing the guide\n'
        ' * line); `extentFrom`/`extentTo` delimit, on the perpendicular axis, the segment spanning both the\n'
        ' * moving object and the matched object, so the drawn guide line visually connects the two.\n'
        ' * `isCenter` is true if either of the two matched candidates was a center point (rather than an\n'
        ' * edge); `isBoosted` is true for the special "small stroke crossing a big perpendicular stroke,\n'
        ' * center-to-center" case (see isSmallCrossingBigPerpendicular()), drawn in a distinct color.\n'
        ' */\n'
        'struct AlignmentMatch {\n'
        '    double offset;\n'
        '    double coordinate;\n'
        '    double extentFrom;\n'
        '    double extentTo;\n'
        '    bool isCenter;\n'
        '    bool isBoosted;\n'
        '};\n\n'
        '/// A single candidate coordinate for alignment, tagged with whether it is a center point.\n'
        'struct AlignmentCandidate {\n'
        '    double value;\n'
        '    bool isCenter;\n'
        '};\n\n'
        '/**\n'
        ' * Below this size (in document points), a box is considered to have no meaningful "thickness axis"\n'
        ' * of its own (e.g. a horizontal or vertical straight line) - see buildCandidates().\n'
        ' */\n'
        'constexpr double THIN_AXIS_THRESHOLD = 3.0;\n\n'
        '/**\n'
        ' * When a small line-like element is moved across a much bigger perpendicular line-like element\n'
        ' * (e.g. a short axis tick dragged onto a long axis line), a center-to-center match between the two\n'
        ' * gets an extended tolerance (this factor) and a distinct guide-line color, since that is a very\n'
        ' * deliberate, common alignment (e.g. centering a graduation mark on an axis).\n'
        ' */\n'
        'constexpr double PERPENDICULAR_CROSS_BOOST_FACTOR = 1.5;\n\n'
        '/**\n'
        ' * Builds the 1 or 3 alignment candidates for a box spanning [from, from + size] on one axis. If the\n'
        ' * box is "thin" on that axis (size <= THIN_AXIS_THRESHOLD, e.g. the thickness of a horizontal or\n'
        ' * vertical line), only the center candidate is returned: offering top/bottom (or left/right)\n'
        ' * candidates as well would produce two near-identical, confusingly close guide lines for a simple\n'
        ' * straight line. `centerFraction` (0 to 1) chooses where that lone candidate sits within the box;\n'
        ' * it is not exactly 0.5 for the horizontal-stroke case (see findAlignmentY()).\n'
        ' */\n'
        'static auto buildCandidates(double from, double size, double centerFraction = 0.5) -> std::vector<AlignmentCandidate> {\n'
        '    if (size <= THIN_AXIS_THRESHOLD) {\n'
        '        return {{from + size * centerFraction, true}};\n'
        '    }\n'
        '    return {{from, false}, {from + size / 2, true}, {from + size, false}};\n'
        '}\n\n'
        '/// True if the two given [x, x+w] x [y, y+h] boxes intersect at all.\n'
        'static auto boxesIntersect(double x1, double y1, double w1, double h1, double x2, double y2, double w2, double h2)\n'
        '        -> bool {\n'
        '    return x1 <= x2 + w2 && x2 <= x1 + w1 && y1 <= y2 + h2 && y2 <= y1 + h1;\n'
        '}\n\n'
        '/**\n'
        ' * True if `self` (width x height) and `other` (width x height) are two line-like boxes (one is\n'
        ' * "thin", per THIN_AXIS_THRESHOLD, on one axis while the other is thin on the *perpendicular* axis -\n'
        ' * i.e. one roughly horizontal, one roughly vertical), AND `self` is shorter, along its own length,\n'
        ' * than `other` is along its own length - i.e. a small stroke crossing a much bigger perpendicular\n'
        ' * one, such as a short axis tick being placed onto a long axis line.\n'
        ' */\n'
        'static auto isSmallCrossingBigPerpendicular(double selfWidth, double selfHeight, double otherWidth,\n'
        '                                             double otherHeight) -> bool {\n'
        '    bool selfVertical = selfWidth <= THIN_AXIS_THRESHOLD && selfHeight > THIN_AXIS_THRESHOLD;\n'
        '    bool selfHorizontal = selfHeight <= THIN_AXIS_THRESHOLD && selfWidth > THIN_AXIS_THRESHOLD;\n'
        '    bool otherVertical = otherWidth <= THIN_AXIS_THRESHOLD && otherHeight > THIN_AXIS_THRESHOLD;\n'
        '    bool otherHorizontal = otherHeight <= THIN_AXIS_THRESHOLD && otherWidth > THIN_AXIS_THRESHOLD;\n\n'
        '    if (selfVertical && otherHorizontal) {\n'
        '        return selfHeight < otherWidth;\n'
        '    }\n'
        '    if (selfHorizontal && otherVertical) {\n'
        '        return selfWidth < otherHeight;\n'
        '    }\n'
        '    return false;\n'
        '}\n\n'
        '/**\n'
        ' * If any of the moving box\'s y-candidates (see buildCandidates()), when placed at the given y with\n'
        ' * the given height, is within `tolerance` (document units) of the corresponding candidate of\n'
        ' * another element on `layer`, returns the match. Candidates are only considered for elements whose\n'
        ' * *visual* bounding box currently intersects `visibleRect` (elements scrolled out of view are\n'
        ' * ignored); the alignment candidates themselves are computed from each element\'s *snapped* bounds\n'
        ' * (Element::getSnappedBounds()) rather than its visual bounds, so that a selected element\'s own\n'
        ' * candidates (computed the same way, from EditSelection::snappedBounds) line up exactly with an\n'
        ' * identical, unselected element\'s - the visual bounds include the stroke\'s rendered thickness,\n'
        ' * which the snapped bounds deliberately exclude.\n'
        ' * elements in `excluded` are always skipped (i.e. the elements currently being moved).\n'
        ' * xLeft/xRight are the moving box\'s horizontal extent, used together with the matched element\'s own\n'
        ' * extent to compute the guide line\'s span (perpendicular axis).\n'
        ' */\n'
        'static auto findAlignmentY(double y, double height, double xLeft, double xRight, double tolerance, Layer* layer,\n'
        '                            const std::vector<const Element*>& excluded,\n'
        '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
        '    // The horizontal-stroke center candidate sits 20% lower than the true geometric center (0.5 + 0.2).\n'
        '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(y, height, 0.7);\n'
        '    std::optional<AlignmentMatch> best;\n'
        '    double bestDist = tolerance;\n'
        '    for (auto& elPtr: layer->getElements()) {\n'
        '        const Element* el = elPtr.get();\n'
        '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
        '            continue;\n'
        '        }\n'
        '        double eh = el->getElementHeight();\n'
        '        double ey = el->getY();\n'
        '        double ew = el->getElementWidth();\n'
        '        double ex = el->getX();\n'
        '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
        '            continue;\n'
        '        }\n'
        '        xoj::util::Rectangle<double> snapped = el->getSnappedBounds();\n'
        '        bool crossBoost = isSmallCrossingBigPerpendicular(xRight - xLeft, height, snapped.width, snapped.height);\n'
        '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(snapped.y, snapped.height, 0.7);\n'
        '        for (auto& cs: candidatesSelf) {\n'
        '            for (auto& co: candidatesOther) {\n'
        '                bool boosted = crossBoost && cs.isCenter && co.isCenter;\n'
        '                double effTolerance = boosted ? tolerance * PERPENDICULAR_CROSS_BOOST_FACTOR : tolerance;\n'
        '                double dist = std::abs(cs.value - co.value);\n'
        '                if (dist < effTolerance && dist < bestDist) {\n'
        '                    bestDist = dist;\n'
        '                    best = AlignmentMatch{co.value - cs.value,\n'
        '                                           co.value,\n'
        '                                           std::min(xLeft, snapped.x),\n'
        '                                           std::max(xRight, snapped.x + snapped.width),\n'
        '                                           cs.isCenter || co.isCenter,\n'
        '                                           boosted};\n'
        '                }\n'
        '            }\n'
        '        }\n'
        '    }\n'
        '    return best;\n'
        '}\n\n'
        '/// Same as findAlignmentY(), but for the horizontal candidates (left / horizontal-center / right).\n'
        '/// yTop/yBottom are the moving box\'s vertical extent, used for the guide line\'s span.\n'
        'static auto findAlignmentX(double x, double width, double yTop, double yBottom, double tolerance, Layer* layer,\n'
        '                            const std::vector<const Element*>& excluded,\n'
        '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
        '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(x, width);\n'
        '    std::optional<AlignmentMatch> best;\n'
        '    double bestDist = tolerance;\n'
        '    for (auto& elPtr: layer->getElements()) {\n'
        '        const Element* el = elPtr.get();\n'
        '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
        '            continue;\n'
        '        }\n'
        '        double ew = el->getElementWidth();\n'
        '        double ex = el->getX();\n'
        '        double eh = el->getElementHeight();\n'
        '        double ey = el->getY();\n'
        '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
        '            continue;\n'
        '        }\n'
        '        xoj::util::Rectangle<double> snapped = el->getSnappedBounds();\n'
        '        bool crossBoost = isSmallCrossingBigPerpendicular(width, yBottom - yTop, snapped.width, snapped.height);\n'
        '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(snapped.x, snapped.width);\n'
        '        for (auto& cs: candidatesSelf) {\n'
        '            for (auto& co: candidatesOther) {\n'
        '                bool boosted = crossBoost && cs.isCenter && co.isCenter;\n'
        '                double effTolerance = boosted ? tolerance * PERPENDICULAR_CROSS_BOOST_FACTOR : tolerance;\n'
        '                double dist = std::abs(cs.value - co.value);\n'
        '                if (dist < effTolerance && dist < bestDist) {\n'
        '                    bestDist = dist;\n'
        '                    best = AlignmentMatch{co.value - cs.value,\n'
        '                                           co.value,\n'
        '                                           std::min(yTop, snapped.y),\n'
        '                                           std::max(yBottom, snapped.y + snapped.height),\n'
        '                                           cs.isCenter || co.isCenter,\n'
        '                                           boosted};\n'
        '                }\n'
        '            }\n'
        '        }\n'
        '    }\n'
        '    return best;\n'
        '}'
    )

    new_block = (
        '/**\n'
        ' * Result of a successful alignment match: `offset` is the amount to shift the moving object\'s\n'
        ' * coordinate to align exactly; `coordinate` is the aligned value itself (for drawing the guide\n'
        ' * line); `extentFrom`/`extentTo` delimit, on the perpendicular axis, the segment spanning both the\n'
        ' * moving object and the matched object, so the drawn guide line visually connects the two.\n'
        ' * `isCenter` is true if either of the two matched candidates was a center point (rather than an\n'
        ' * edge); `isBoosted` is true for the special "small stroke crossing a big perpendicular stroke,\n'
        ' * center-to-center" case (see isSmallCrossingBigPerpendicular()), drawn in a distinct color.\n'
        ' */\n'
        'struct AlignmentMatch {\n'
        '    double offset;\n'
        '    double coordinate;\n'
        '    double extentFrom;\n'
        '    double extentTo;\n'
        '    bool isCenter;\n'
        '    bool isBoosted;\n'
        '};\n\n'
        '/// A single candidate coordinate for alignment, tagged with whether it is a center point.\n'
        'struct AlignmentCandidate {\n'
        '    double value;\n'
        '    bool isCenter;\n'
        '};\n\n'
        '/**\n'
        ' * Below this size (in document points), a box is considered to have no meaningful "thickness axis"\n'
        ' * of its own (e.g. a horizontal or vertical straight line) - see buildCandidates().\n'
        ' */\n'
        'constexpr double THIN_AXIS_THRESHOLD = 3.0;\n\n'
        '/**\n'
        ' * When a small line-like element is moved across a much bigger perpendicular line-like element\n'
        ' * (e.g. a short axis tick dragged onto a long axis line), a center-to-center match between the two\n'
        ' * gets an extended tolerance (this factor), takes priority over any other match on that axis (see\n'
        ' * findAlignmentX/Y()), and is drawn in a distinct color, since that is a very deliberate, common\n'
        ' * alignment (e.g. centering a graduation mark on an axis).\n'
        ' */\n'
        'constexpr double PERPENDICULAR_CROSS_BOOST_FACTOR = 1.5;\n\n'
        '/**\n'
        ' * The "small stroke crossing a big perpendicular stroke" boost only applies if the small stroke\'s\n'
        ' * own length (its extent along its own axis, e.g. a vertical tick\'s height) is at most this many\n'
        ' * document points - the same unit used for arrow-key nudging.\n'
        ' */\n'
        'constexpr double PERPENDICULAR_CROSS_MAX_SELF_LENGTH = 15.0;\n\n'
        '/**\n'
        ' * Fraction (0 to 1, from the top) of a Text element\'s height used as its horizontal-alignment (Y)\n'
        ' * anchor, instead of the true geometric center (0.5). Text bounding boxes include descender space\n'
        ' * below the baseline, which pulls the geometric center lower than where a horizontal alignment\n'
        ' * "feels" visually centered on the text - this constant lets that be tuned independently of\n'
        ' * everything else. Deliberately left at an easily-noticeable default; tune to taste.\n'
        ' */\n'
        'constexpr double TEXT_Y_CENTER_FRACTION = 0.2;\n\n'
        '/**\n'
        ' * Builds the 1 or 3 alignment candidates for a box spanning [from, from + size] on one axis. If the\n'
        ' * box is "thin" on that axis (size <= THIN_AXIS_THRESHOLD, e.g. the thickness of a horizontal or\n'
        ' * vertical line), only the center candidate is returned: offering top/bottom (or left/right)\n'
        ' * candidates as well would produce two near-identical, confusingly close guide lines for a simple\n'
        ' * straight line. `centerFraction` (0 to 1) chooses where that lone candidate sits within the box.\n'
        ' */\n'
        'static auto buildCandidates(double from, double size, double centerFraction = 0.5) -> std::vector<AlignmentCandidate> {\n'
        '    if (size <= THIN_AXIS_THRESHOLD) {\n'
        '        return {{from + size * centerFraction, true}};\n'
        '    }\n'
        '    return {{from, false}, {from + size / 2, true}, {from + size, false}};\n'
        '}\n\n'
        '/// True if the two given [x, x+w] x [y, y+h] boxes intersect at all.\n'
        'static auto boxesIntersect(double x1, double y1, double w1, double h1, double x2, double y2, double w2, double h2)\n'
        '        -> bool {\n'
        '    return x1 <= x2 + w2 && x2 <= x1 + w1 && y1 <= y2 + h2 && y2 <= y1 + h1;\n'
        '}\n\n'
        '/// True if the two given ranges [a1, a2] and [b1, b2] overlap at all.\n'
        'static auto rangesOverlap(double a1, double a2, double b1, double b2) -> bool { return a1 <= b2 && b1 <= a2; }\n\n'
        '/**\n'
        ' * True if `self` (width x height) and `other` (width x height) are two line-like boxes (one is\n'
        ' * "thin", per THIN_AXIS_THRESHOLD, on one axis while the other is thin on the *perpendicular* axis -\n'
        ' * i.e. one roughly horizontal, one roughly vertical), `self` is shorter, along its own length, than\n'
        ' * `other` is along its own length, AND `self`\'s own length is at most PERPENDICULAR_CROSS_MAX_SELF_LENGTH\n'
        ' * - i.e. a small stroke crossing a much bigger perpendicular one, such as a short axis tick being\n'
        ' * placed onto a long axis line. Does NOT check whether they actually currently overlap in position -\n'
        ' * see rangesOverlap(), checked separately by the caller, which has the position information.\n'
        ' */\n'
        'static auto isSmallCrossingBigPerpendicular(double selfWidth, double selfHeight, double otherWidth,\n'
        '                                             double otherHeight) -> bool {\n'
        '    bool selfVertical = selfWidth <= THIN_AXIS_THRESHOLD && selfHeight > THIN_AXIS_THRESHOLD;\n'
        '    bool selfHorizontal = selfHeight <= THIN_AXIS_THRESHOLD && selfWidth > THIN_AXIS_THRESHOLD;\n'
        '    bool otherVertical = otherWidth <= THIN_AXIS_THRESHOLD && otherHeight > THIN_AXIS_THRESHOLD;\n'
        '    bool otherHorizontal = otherHeight <= THIN_AXIS_THRESHOLD && otherWidth > THIN_AXIS_THRESHOLD;\n\n'
        '    if (selfVertical && otherHorizontal) {\n'
        '        return selfHeight < otherWidth && selfHeight <= PERPENDICULAR_CROSS_MAX_SELF_LENGTH;\n'
        '    }\n'
        '    if (selfHorizontal && otherVertical) {\n'
        '        return selfWidth < otherHeight && selfWidth <= PERPENDICULAR_CROSS_MAX_SELF_LENGTH;\n'
        '    }\n'
        '    return false;\n'
        '}\n\n'
        '/**\n'
        ' * If any of the moving box\'s y-candidates (see buildCandidates()) is within `tolerance` (document\n'
        ' * units) of the corresponding candidate of another element on `layer`, returns the match. Elements\n'
        ' * whose *visual* bounding box doesn\'t currently intersect `visibleRect` are ignored (scrolled out of\n'
        ' * view); elements in `excluded` are always skipped (i.e. the elements currently being moved).\n'
        ' * Candidates are computed from each element\'s *snapped* bounds (Element::getSnappedBounds()) rather\n'
        ' * than its visual bounds, so that a selected element\'s own candidates line up exactly with an\n'
        ' * identical, unselected element\'s - the visual bounds include the stroke\'s rendered thickness, which\n'
        ' * the snapped bounds deliberately exclude. A Text element\'s center candidate uses\n'
        ' * TEXT_Y_CENTER_FRACTION instead of the true geometric center.\n'
        ' *\n'
        ' * Matches are prioritized in three tiers, each considered only if the previous one found nothing:\n'
        ' * a "boosted" perpendicular-cross center match (see isSmallCrossingBigPerpendicular()), then any\n'
        ' * match involving a center candidate, then any match at all (including edge-only). A tier, once it\n'
        ' * has a match, always wins over a later tier even if a later tier\'s match would have been closer.\n'
        ' *\n'
        ' * xLeft/xRight are the moving box\'s horizontal extent, used both for the crossing/overlap check and\n'
        ' * to compute the guide line\'s span (perpendicular axis).\n'
        ' */\n'
        'static auto findAlignmentY(double y, double height, double xLeft, double xRight, double tolerance, Layer* layer,\n'
        '                            const std::vector<const Element*>& excluded,\n'
        '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
        '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(y, height);\n\n'
        '    std::optional<AlignmentMatch> bestBoosted;\n'
        '    double bestBoostedDist = tolerance * PERPENDICULAR_CROSS_BOOST_FACTOR;\n'
        '    std::optional<AlignmentMatch> bestCenter;\n'
        '    double bestCenterDist = tolerance;\n'
        '    std::optional<AlignmentMatch> bestAny;\n'
        '    double bestAnyDist = tolerance;\n\n'
        '    for (auto& elPtr: layer->getElements()) {\n'
        '        const Element* el = elPtr.get();\n'
        '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
        '            continue;\n'
        '        }\n'
        '        double eh = el->getElementHeight();\n'
        '        double ey = el->getY();\n'
        '        double ew = el->getElementWidth();\n'
        '        double ex = el->getX();\n'
        '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
        '            continue;\n'
        '        }\n'
        '        xoj::util::Rectangle<double> snapped = el->getSnappedBounds();\n'
        '        double otherCenterFraction = dynamic_cast<const Text*>(el) != nullptr ? TEXT_Y_CENTER_FRACTION : 0.5;\n'
        '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(snapped.y, snapped.height, otherCenterFraction);\n\n'
        '        bool crossEligible = isSmallCrossingBigPerpendicular(xRight - xLeft, height, snapped.width, snapped.height) &&\n'
        '                              rangesOverlap(xLeft, xRight, ex, ex + ew);\n\n'
        '        for (auto& cs: candidatesSelf) {\n'
        '            for (auto& co: candidatesOther) {\n'
        '                double dist = std::abs(cs.value - co.value);\n'
        '                bool isCenterPair = cs.isCenter && co.isCenter;\n'
        '                AlignmentMatch candidate{co.value - cs.value,\n'
        '                                          co.value,\n'
        '                                          std::min(xLeft, snapped.x),\n'
        '                                          std::max(xRight, snapped.x + snapped.width),\n'
        '                                          cs.isCenter || co.isCenter,\n'
        '                                          false};\n\n'
        '                if (crossEligible && isCenterPair && dist < bestBoostedDist) {\n'
        '                    bestBoostedDist = dist;\n'
        '                    candidate.isBoosted = true;\n'
        '                    bestBoosted = candidate;\n'
        '                }\n'
        '                if ((cs.isCenter || co.isCenter) && dist < bestCenterDist) {\n'
        '                    bestCenterDist = dist;\n'
        '                    bestCenter = candidate;\n'
        '                }\n'
        '                if (dist < bestAnyDist) {\n'
        '                    bestAnyDist = dist;\n'
        '                    bestAny = candidate;\n'
        '                }\n'
        '            }\n'
        '        }\n'
        '    }\n\n'
        '    if (bestBoosted) {\n'
        '        return bestBoosted;\n'
        '    }\n'
        '    if (bestCenter) {\n'
        '        return bestCenter;\n'
        '    }\n'
        '    return bestAny;\n'
        '}\n\n'
        '/// Same as findAlignmentY(), but for the horizontal candidates (left / horizontal-center / right).\n'
        '/// yTop/yBottom are the moving box\'s vertical extent, used for the crossing/overlap check and the\n'
        '/// guide line\'s span. Unlike findAlignmentY(), there is no Text-specific center fraction here.\n'
        'static auto findAlignmentX(double x, double width, double yTop, double yBottom, double tolerance, Layer* layer,\n'
        '                            const std::vector<const Element*>& excluded,\n'
        '                            const xoj::util::Rectangle<double>& visibleRect) -> std::optional<AlignmentMatch> {\n'
        '    const std::vector<AlignmentCandidate> candidatesSelf = buildCandidates(x, width);\n\n'
        '    std::optional<AlignmentMatch> bestBoosted;\n'
        '    double bestBoostedDist = tolerance * PERPENDICULAR_CROSS_BOOST_FACTOR;\n'
        '    std::optional<AlignmentMatch> bestCenter;\n'
        '    double bestCenterDist = tolerance;\n'
        '    std::optional<AlignmentMatch> bestAny;\n'
        '    double bestAnyDist = tolerance;\n\n'
        '    for (auto& elPtr: layer->getElements()) {\n'
        '        const Element* el = elPtr.get();\n'
        '        if (std::find(excluded.begin(), excluded.end(), el) != excluded.end()) {\n'
        '            continue;\n'
        '        }\n'
        '        double ew = el->getElementWidth();\n'
        '        double ex = el->getX();\n'
        '        double eh = el->getElementHeight();\n'
        '        double ey = el->getY();\n'
        '        if (!boxesIntersect(ex, ey, ew, eh, visibleRect.x, visibleRect.y, visibleRect.width, visibleRect.height)) {\n'
        '            continue;\n'
        '        }\n'
        '        xoj::util::Rectangle<double> snapped = el->getSnappedBounds();\n'
        '        std::vector<AlignmentCandidate> candidatesOther = buildCandidates(snapped.x, snapped.width);\n\n'
        '        bool crossEligible = isSmallCrossingBigPerpendicular(width, yBottom - yTop, snapped.width, snapped.height) &&\n'
        '                              rangesOverlap(yTop, yBottom, ey, ey + eh);\n\n'
        '        for (auto& cs: candidatesSelf) {\n'
        '            for (auto& co: candidatesOther) {\n'
        '                double dist = std::abs(cs.value - co.value);\n'
        '                bool isCenterPair = cs.isCenter && co.isCenter;\n'
        '                AlignmentMatch candidate{co.value - cs.value,\n'
        '                                          co.value,\n'
        '                                          std::min(yTop, snapped.y),\n'
        '                                          std::max(yBottom, snapped.y + snapped.height),\n'
        '                                          cs.isCenter || co.isCenter,\n'
        '                                          false};\n\n'
        '                if (crossEligible && isCenterPair && dist < bestBoostedDist) {\n'
        '                    bestBoostedDist = dist;\n'
        '                    candidate.isBoosted = true;\n'
        '                    bestBoosted = candidate;\n'
        '                }\n'
        '                if ((cs.isCenter || co.isCenter) && dist < bestCenterDist) {\n'
        '                    bestCenterDist = dist;\n'
        '                    bestCenter = candidate;\n'
        '                }\n'
        '                if (dist < bestAnyDist) {\n'
        '                    bestAnyDist = dist;\n'
        '                    bestAny = candidate;\n'
        '                }\n'
        '            }\n'
        '        }\n'
        '    }\n\n'
        '    if (bestBoosted) {\n'
        '        return bestBoosted;\n'
        '    }\n'
        '    if (bestCenter) {\n'
        '        return bestCenter;\n'
        '    }\n'
        '    return bestAny;\n'
        '}'
    )

    ok &= apply_edit(cpp, old_block, new_block,
                      "EditSelection.cpp: réécriture findAlignmentX/Y (priorité paliers + intersection + textes)")

    ok &= apply_edit(
        cpp,
        old='            if (this->activeGuideX->isBoosted) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.4, 1.0);  // blue\n'
            '            } else if (this->activeGuideX->isCenter) {',
        new='            if (this->activeGuideX->isBoosted) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.55, 1.0);  // vivid electric blue\n'
            '            } else if (this->activeGuideX->isCenter) {',
        label="EditSelection.cpp: bleu plus vif (activeGuideX)",
    )
    ok &= apply_edit(
        cpp,
        old='            if (this->activeGuideY->isBoosted) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.4, 1.0);  // blue\n'
            '            } else if (this->activeGuideY->isCenter) {',
        new='            if (this->activeGuideY->isBoosted) {\n'
            '                cairo_set_source_rgb(cr, 0.0, 0.55, 1.0);  // vivid electric blue\n'
            '            } else if (this->activeGuideY->isCenter) {',
        label="EditSelection.cpp: bleu plus vif (activeGuideY)",
    )

    print()
    if ok:
        print("Toutes les modifications ont été appliquées avec succès.")
        sys.exit(0)
    else:
        print("Au moins une modification a échoué. Vérifiez le [ECHEC] ci-dessus.")
        sys.exit(1)


if __name__ == "__main__":
    main()
